class GameConstants
  FIGHT_OPTION = :fight
  RUN_OPTION = :run
  PLAYER_EXITED = :exit
  LEVEL_FINISHED = :finished_current_level
  FIGHT_LOST = :defeated
  FIGHT_WON = :won
  RETURN_TO_PREIVOUS_ROOM = :back
  CHOICE_TRIAL = 3
  RIGHT = :right
  LEFT = :left
  FORWARD = :forward
  BACKWORD = :backword
  ROOM_STRING_SPLITER = "@@"
  ROOM_STRING_CLASS_INDEX = 0
  ROOM_STRING_WEAPONS_INDEX = 1
  ROOM_STRING_SCORE_INDEX = 2
  GAME_ENTRANCE_MSG = "VALLEY OF THE DEAD SAYS : WHO DARES TO ENTER VALLEY OF THE DEAD?!!!"
  LEVEL1_FINISHING_MSG = "VALLEY OF THE DEAD SAYS : YOU SERVIVED SO FAR!, BUT IT WON'T LAST FOR LONG"
  LEVEL2_FINISHING_MSG = "VALLEY OF THE DEAD SAYS : Now you are the new master of valley of the dead"
  GAME_EXIT_MSG = "VALLEY OF THE DEAD SAYS : you were warned you from entering valley of the dead, YOU WILL THINK TWICE BEFORE COMING AGAIN"
  INVALID_CHOICE_MSG = "[GAME] Invalid choice, please enter a valid choice or type exit to end the game"
  WEAPONS_FOUND_MSG = " more hostages! we freed them and they joined us, now we are "
  SCORE_ADDED_MSG = "[GAME] Your score is now "
  YOUR_ARMY_PREFIX = "YOUR ARMY SAYS : "
  VALLEY_OF_THE_DEAD_PREFIX = "VALLEY OF THE DEAD SAYS : "
  EMPTY_ROOM_ENTRY_MSG = "YOUR ARMY SAYS : It is an empty spot, nothing here."
  EMPTY_ROOM_NAVIGATION_MSG = "YOUR ARMY SAYS : where should we go next?"
  FIGHT_OPTIONS_MSG = "YOUR ARMY SAYS : what should we do?"
  EXCEEDED_CHOICES_TRIALS = "[GAME] You exceeded the allowed trials for providing choices, you will exit the game"
  ARMY_ENTERED_NEW_LEVEL = "YOUR ARMY SAYS : there is still more place to go ?!!"
  FIGHT_CAN_BE_SKIPPED_MSG = " GUARDS ARE HERE! LET'S SEE IF YOU CAN BEAT THEM"
  FIGHT_CAN_NOT_BE_SKIPPED_MSG = " GUARDS ARE HERE! THEY ARE PREPARED AND YOU WILL NOT BE ABLE TO RUN THIS TIME"
  FIGHT_SKIPPED_MSG = "VALLEY OF THE DEAD SAYS : YOU WILL NOT RUN FOR EVER, NEXT TIME MY GUARDS WILL BE PREPARED\nYOUR ARMY SAYS : we returned to the previous room"
  FIGHT_WON_MSG = "YOUR ARMY SAYS : WE DEFEATED THEM!!"
  FIGHT_LOST_MSG = "VALLEY OF THE DEAD SAYS : GUARDS OF VALLEY OF THE DEAD TOUGHT YOU A LESSON AND DEFEATED YOU"
  INPUT_TAKING_MSG = "[GAME] Your choice is : "
end
